export enum AuthErrorTypes {
    USER_EXISTS = 'USER_EXISTS',
    REGISTRATION_FAIL = 'REGISTRATION_FAIL',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    MISSING_CREDENTIALS = 'MISSING_CREDENTIALS',
}
